pipeline {
agent any

tools {
    maven 'Maven3'
    jdk 'JDK'
}

stages {

    stage('Checkout') {
        steps {
            git branch: 'main',
                url: 'https://github.com/2002Umesh/VM_Test'
        }
    }

    stage('Build') {
        steps {
            dir('New_Test') {
                bat 'mvn clean'
            }
        }
    }

    stage('Compile') {
        steps {
            dir('New_Test') {
                bat 'mvn compile'
            }
        }
    }

    stage('Test') {
        steps {
            dir('New_Test') {
                bat 'mvn test'
            }
        }

        post {
            always {
                junit 'New_Test/target/surefire-reports/*.xml'
            }
        }
    }

    stage('Package') {
        steps {
            dir('New_Test') {
                bat 'mvn package'
            }
        }
    }
}

post {
    success {
        echo 'Build Successful'
    }

    failure {
        echo 'Build Failed'
    }
}

}