pipeline {
agent any

tools {
    maven 'Maven3'
    jdk 'JDK'
}

stages {

    stage('Checkout') {
        steps {
            git branch: 'main',
                url: 'https://github.com/2002Umesh/VM_Test'
        }
    }

    stage('Build') {
        steps {
            dir('New_Test') {
                bat 'mvn clean'
            }
        }
    }

    stage('Compile') {
        steps {
            dir('New_Test') {
                bat 'mvn compile'
            }
        }
    }

    stage('Docker Build') {
        steps {
            dir('New_Test') {
                bat 'docker build -t vm-test-framework .'
            }
        }
    }

    stage('Docker Test') {
        steps {
            dir('New_Test') {
                bat 'docker run --rm vm-test-framework'
            }
        }
    }
}

post {
    success {
        echo 'Build Successful'
    }

    failure {
        echo 'Build Failed'
    }
}

}